// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urbbngcarxdqesenfvsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyYmJuZ2NhcnhkcWVzZW5mdnNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5MTU4NzcsImV4cCI6MjA3NzQ5MTg3N30.QL3fBw7d_eaAF4yN8FDfzLQ_pOq-9u8B80PGHByqfas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});